# Generated by Django 4.1.3 on 2022-11-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProfes', '0002_delete_entregable_remove_curso_comision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='curso',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiante',
            name='institucion',
            field=models.CharField(default=2, max_length=40),
            preserve_default=False,
        ),
    ]
